server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/good?autoReconnect=true&useSSL=false
    username: root
    password: Mysql@1239
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

#bind-address: 0.0.0.0
